/* tslint:disable */
/* eslint-disable */
/**
 * Saferwall Web API
 * Interact with Saferwall Malware Analysis Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@saferwall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

